import enum

class ModerationCategory(str, enum.Enum):
    SEXUAL = "SEXUAL"
    SEXUAL_EXPLICIT = "SEXUAL_EXPLICIT"
    SEXUAL_MINORS = "SEXUAL_MINORS"
    VIOLENCE = "VIOLENCE"
    GRAPHIC_VIOLENCE = "GRAPHIC_VIOLENCE"
    THREAT = "THREAT"
    HATE = "HATE"
    RACISM = "RACISM"
    ANTISEMITISM = "ANTISEMITISM"
    RELIGIOUS_HATE = "RELIGIOUS_HATE"
    SEXISM = "SEXISM"
    HOMOPHOBIA = "HOMOPHOBIA"
    TRANSPHOBIA = "TRANSPHOBIA"
    DISCRIMINATION = "DISCRIMINATION"
    HARASSMENT = "HARASSMENT"
    EXTREMISM = "EXTREMISM"
    ILLEGAL_ACTIVITY = "ILLEGAL_ACTIVITY"
    SPAM = "SPAM"
    ADVERTISEMENT = "ADVERTISEMENT"
    ABUSE = "ABUSE"
    EVASION = "EVASION"
    OFF_TOPIC = "OFF_TOPIC"
    SAFE = "SAFE"


class ModerationSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ModerationAction(str, enum.Enum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    CRITICAL_BLOCK = "CRITICAL_BLOCK"
